# Generated by Django 4.1.4 on 2022-12-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='onlineShop.city'),
            preserve_default=False,
        ),
    ]
