# Generated by Django 4.1.4 on 2022-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0002_area_city_idcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_fullname',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
