# Generated by Django 4.1.4 on 2023-01-05 16:57

from django.db import migrations, models
import onlineShop.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0004_alter_user_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=onlineShop.models.filepath),
        ),
    ]
