# Generated by Django 4.1.4 on 2023-01-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0005_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city_idcity',
            field=models.ForeignKey(db_column='city_idcity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.city'),
        ),
        migrations.AlterField(
            model_name='store',
            name='area_pincode',
            field=models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_pincode',
            field=models.ForeignKey(db_column='area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='store_idstore',
            field=models.ForeignKey(db_column='store_idstore', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.store'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('idbrand', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=45)),
                ('brand_description', models.CharField(max_length=200)),
                ('store_idstore', models.ForeignKey(db_column='store_idstore', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.store')),
            ],
            options={
                'db_table': 'brand',
                'managed': True,
            },
        ),
    ]
