# Generated by Django 4.1.4 on 2023-02-06 10:02

from django.db import migrations, models
import django.db.models.deletion
import onlineShop.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0006_alter_area_city_idcity_alter_store_area_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('idOffer', models.AutoField(primary_key=True, serialize=False)),
                ('offer_start_date', models.DateField()),
                ('offer_end_date', models.DateField()),
                ('offer_description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to=onlineShop.models.filepathProduct)),
                ('product_description', models.TextField(max_length=3000)),
                ('offer_offer_idOffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.offer')),
            ],
        ),
    ]
