# Generated by Django 4.1.4 on 2023-02-06 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0007_offer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_brand_idbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.brand'),
        ),
    ]
