# Generated by Django 4.1.4 on 2023-02-09 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0008_product_brand_brand_idbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineShop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineShop.user')),
            ],
        ),
    ]
