# Generated by Django 4.1.4 on 2023-02-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer_record',
            field=models.IntegerField(default=0),
        ),
    ]
