# Generated by Django 4.1.4 on 2023-02-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0012_cart_offer_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.AutoField(primary_key=True, serialize=False)),
                ('orderfname', models.CharField(max_length=150, null=True)),
                ('orderlname', models.CharField(max_length=150, null=True)),
                ('orderemail', models.CharField(max_length=150, null=True)),
                ('ordermobile', models.CharField(max_length=150, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_delivery_date', models.DateTimeField(auto_now_add=True)),
                ('order_delivery_address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('total_amount', models.FloatField()),
                ('order_payment_method', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Out for shipping', 'Out for shipping'), ('Completed', 'Completed')], default='Pending', max_length=150)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('is_cancel_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('area_pincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.area')),
                ('user_iduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.user')),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order_idorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.order')),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.product')),
            ],
            options={
                'db_table': 'ordered_item',
                'managed': True,
            },
        ),
    ]
