# Generated by Django 4.1.4 on 2023-02-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0013_order_ordereditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderfname',
            new_name='orderfullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderlname',
        ),
    ]
