# Generated by Django 4.1.6 on 2023-02-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0014_rename_orderfname_order_orderfullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesories',
            fields=[
                ('idaccesories', models.AutoField(primary_key=True, serialize=False)),
                ('accesories_name', models.CharField(max_length=45)),
                ('accesories_description', models.CharField(max_length=200)),
                ('store_idstore', models.ForeignKey(db_column='store_idstore', null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.store')),
            ],
            options={
                'db_table': 'accesories',
                'managed': True,
            },
        ),
    ]
