# Generated by Django 4.1.6 on 2023-02-26 05:52

from django.db import migrations, models
import django.db.models.deletion
import onlineShop.models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0015_accesories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesories_Pro',
            fields=[
                ('idaccesories', models.AutoField(primary_key=True, serialize=False)),
                ('accesories_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('accesories_image', models.ImageField(upload_to=onlineShop.models.filepathProduct)),
                ('accesories_description', models.TextField(max_length=3000)),
                ('accesories_accesories_idaccesories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.brand')),
                ('offer_offer_idOffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.offer')),
            ],
        ),
    ]
