# Generated by Django 4.1.6 on 2023-03-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0016_accesories_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='accesories_pro',
            name='accesories_accesories_idaccesories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.accesories'),
        ),
    ]
