# Generated by Django 4.1.6 on 2023-03-05 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0017_store_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.accesories'),
        ),
    ]
