# Generated by Django 4.1.6 on 2023-03-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0018_cart_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accessories_qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
