# Generated by Django 4.1.6 on 2023-03-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineShop', '0019_cart_accessories_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineShop.accesories_pro'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='accessories_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
